### ISSUE TITLE
Comment period is closed

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#107]
What does the tool look like when the comment period closes?

**Comment by jehlers** [comment]
Initial ideas:

- Sidebar paragraph and headline level links to "write a comment" disabled and disappear. 
- Read/Write mode tabs removed.
- Read/Write mode tabs stay, but write mode now has a message "The comment period for this rule is closed." Maybe points to the docket w/ all the public comments.
- Homepage mentions the closed comment period.
- ...

**Comment by jehlers** [comment]
From @donjo: I think: 
- homepage copy change, grey out/disable write mode tab but leave it there so people see how the tool works (hover tooltip would tell you that it is disabled because the comment period is closed), 
- and then maybe removing the “write a comment” links next to the paragraph
- and lastly changing the “Comment Period Ends” think that exists in the top right corner (which we haven’t implemented yet) to say “Comment Period Has Ended” with a link to the docket

**Comment by jehlers** [comment]
So it sounds like we agree on the following:

- Hide sidebar links to "write a comment" 
- Changing the preamble introduction (https://github.com/eregs/notice-and-comment/issues/106#issuecomment-212603007) and homepage (still working) to mention the closed comment period 
- Taking away the date from the right sidebar and replacing it with "Comment period has ended"

What's in question - Should we:

- Disable the write tab and show a tool tip that explains the comment period is closed if someone tries to click on it? Or
- Allow the write tab to be clicked on, but replace write mode with a message that explains the comment period is over and sends users to the docket folder with all the comments?

**Comment by donjo** [comment]
Now that you bring up the mobile thing I think maybe just doing one solution for both mobile and desktop where clicking the tab takes you to a page that explains how the comment period is closed is probably the right direction. 

And I agree with the other things you mentioned.

**Comment by jehlers** [comment]
OK - final decision: 

- Hide sidebar links to "write a comment" 
- Changing the preamble introduction (https://github.com/eregs/notice-and-comment/issues/106#issuecomment-212603007) and homepage (still working) to mention the closed comment period 
- Taking away the date from the right sidebar and replacing it with "Comment period has ended"
- Allow the write tab to be clicked on, but replace write mode with a message that explains the comment period is over and sends users to the docket folder with all the comments
