### ISSUE TITLE
Implement collapsed stars

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#108]
Currently, we show the _whole_ section in the CFR changes, even when only a few paragraphs are changing. We need a mechanism to tag paragraphs that should be hidden until collapsed.

For a first pass, something like:
```
(a) Intro
    (1) Some subparagraph
(b) Intro for b
    (1) Sub b
    (2) [CHANGE IS HERE]
    (3) Content
    (4) 4 Content
(c) C Content
(d) D Content
(e) E Content
```
being displayed as
```
* * * Expandable * * *
(b) * * * Expandable * * *
    (2) [CHANGE IS HERE]
    * * * Expandable * * *
* * * Expandable * * *
```
seems okay. We can follow up to add a list of paragraphs in the "Expandable" text and possibly combine the last two "Expandable"s in the above.

A tricky bit: multiple paragraphs may have changed.

@jehlers does all that sound right?

**Comment by jehlers** [comment]
@cmc333333 I think so! Are each of those paragraphs individually expandable? I was thinking something like:

§ section title
* * * Expandable starts * * *
(a) paragraph
(b) paragraph
* * * Expandable ends * * *
(c) change happens here
     (1) more change
     (2) more changes
* * * Expandable starts * * *
(d) more paragraphs
(e) more paragraphs
     (1) more more
     (2) more more
(f) more paragraphs
* * * Expandable ends * * *
(g) change happens here

Is that the same as what you're thinking?

**Comment by cmc333333** [comment]
@jehlers almost -- what happens if there is no change in (c) or (c)(1), but only a change in (c)(2)?

**Comment by jehlers** [comment]
#125 Has the latest design for these.

**Comment by xtine** [comment]
@cmc333333: just realized that the mocks show previous and next sections. Are we still implementing that?

**Comment by cmc333333** [comment]
@xtine yes, that's #113

**Comment by donjo** [comment]
This is good to go, correct?

**Comment by xtine** [comment]
Implemented, closing issue.
