### ISSUE TITLE
Footer navigation

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#113]
We can navigate between sections of the notice via the ToC right now, but we should also have navigation in the footer of every page (as we do with the CFR viewer)

**Comment by jmcarp** [comment]
The CFR viewer seems to use a flat toc (is that right?), which makes prev/back interactions simple. The preamble toc and routes are nested, so I'm less clear on how navigation should work--should we show next/prev siblings? What if we're showing III-D, and that's the last sub-section of III--should we have a next button for IV-A?

Also wondering whether we want to move preamble toc generation from the templates to python (like `CFRChangeToc`), or into -core (that's where the reg tocs come from, right?) before we implement this.

**Comment by cmc333333** [comment]
Nesting should go away in #109; +1 on not generating the ToC in the template.

**Comment by jmcarp** [comment]
The screenshot in #80 looks kind of nested--we're showing three levels of hierarchy in the toc, right? Based on that image, would the next nav after II-a be III? III-B?

**Comment by cmc333333** [comment]
Per #109, users won't be navigated to `II-a`, they'll be on `II#II-a` (or similar). For generality, we can link to the next/previous top-level section, even when a user types `/preamble/XXXX/II/a` in their browser.
