### ISSUE TITLE
Handle failures to submit

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#114]
Should regs.gov be down or not accept a comment X number of times, we need a backup. We should be able to

1) Easily find that error (notifications?)
2) Pull down the documents for sending via alternative means (e.g. email)

Note that right now, tasks which fail X number of times _drop_.

**Comment by vrajmohan** [comment]
This was fixed in https://github.com/eregs/regulations-site/commit/6351de894a10c59cd6d86969b92f6ebfa1f81e4d.
