### ISSUE TITLE
Implement CAPTCHA?

### ISSUE THREAD

**Issue by vrajmohan** [eregs/notice-and-comment#123]
To prevent malicious submissions of comments. Somewhat related to https://github.com/eregs/notice-and-comment/issues/111.  Fixing that will help mitigate this issue.

**Comment by cmc333333** [comment]
I don't think this would gain us too much, but would cost us a lot in terms of usability

**Comment by vrajmohan** [comment]
Agree that this will reduce usability considerably. We should definitely address #111.
