### ISSUE TITLE
Add "draft" watermark indication to document downloaded before submission

### ISSUE THREAD

**Issue by vrajmohan** [eregs/notice-and-comment#124]
Preview document downloaded before the user submits their comment to regs.gov should have a draft "watermark."

It should probably be more of a header than a watermark so that a user who wants to copy and paste the comment text does not have any issues with that.

https://trello.com/c/8k8VAXji

**Comment by cmc333333** [comment]
I wonder if it'd make sense to just have a background image on the PDF with a light grey (or pink) "DRAFT", e.g. 
![](http://www.nwarwick.co.uk/Office2003/images/AccessReportWatermarks2.gif)

**Comment by vrajmohan** [comment]
I was thinking the same thing. After all, the intent is to prevent the user from _misinterpreting_ the document rather than _protecting_ the document.

**Comment by vrajmohan** [comment]
We need the watermark only in the PDF, right? We _don't_ want to watermark the review as HTML. I have used https://github.com/pmaupin/pdfrw/blob/master/examples/watermark.py to create a sample watermarked comment.
[watermark.comment.pdf](https://github.com/eregs/notice-and-comment/files/232161/watermark.comment.pdf)

I'll work on implementing this. The actual watermark is a single page PDF file that can be easily replaced.

**Comment by cmc333333** [comment]
Is there a way to implement it by inserting some html text and styles? It'd be nice to avoid adding another library

**Comment by vrajmohan** [comment]
Yes, it is easy enough to do it that way. Something like http://codepen.io/YuvarajTana/pen/auiqx would work as well.

**Comment by jehlers** [comment]
Do we now have a duplicate with #208?

**Comment by vrajmohan** [comment]
Using a stylesheet to add a background image or text works on the HTML, but doesn't seem to survive the PDF conversion. The image only shows up on the 1st page. See 
[comment (13).pdf](https://github.com/eregs/notice-and-comment/files/237558/comment.13.pdf).

We have 2 other options:
1. Use https://github.com/pmaupin/pdfrw/blob/master/examples/watermark.py as mentioned in an earlier comment. It does add a dependency on a somewhat less popular library.
2. Use `wkhtmltopdf --footer-center DRAFT`to add a footer on every page. A `header` option is also available. This does not look as nice as a watermark image but it is the easiest to implement.

I am open to suggestions.

**Comment by cmc333333** [comment]
@vrajmohan Would it be feasible to use a tiled background image?

**Comment by vrajmohan** [comment]
@cmc333333: That works (almost) like a charm. Thanks.
