### ISSUE TITLE
add text description to comment builder

### ISSUE THREAD

**Issue by donjo** [eregs/notice-and-comment#136]
The write mode tab should have a section that verbally describes how your pieces of commentary are being linked together to form the larger comment including a count of how many pieces of commentary you've saved so far.

![screen shot 2016-04-12 at 2 50 43 pm](https://cloud.githubusercontent.com/assets/776987/14473494/04b0e546-00be-11e6-8eaf-880456b3794a.png)

**Comment by jehlers** [comment]
We can talk about this more after the usability tests tomorrow, but maybe to help introduce people to this sidebar section we could separate those words in a way that may lead them through. Something maybe like this:

**Your comments** (title)
You have X comments pending.
[ comment section II.A ]
[ comment section II.A.4.i ] 
[ comment section II.B.3 ]
Are you ready to review and submit your full comment?
{Review and submit}

What do you think @donjo?
