### ISSUE TITLE
write mode text preview polish

### ISSUE THREAD

**Issue by donjo** [eregs/notice-and-comment#138]
The area in write mode that shows the user which section they are commenting on needs some polish. Either making it so only the first and last parts of the quoted section are displayed or some styling to indicate that users can scroll in that quoted area. 

_note: this is the area that needs to be addressed **not** the way it should look_ 
![screen shot 2016-04-12 at 2 55 45 pm](https://cloud.githubusercontent.com/assets/776987/14473654/ba873dc0-00be-11e6-9a7b-c411f3e5a96a.png)

**Comment by jehlers** [comment]
I think we need to also consistently have the citation listed in some way, so that it matches the comment sidebar and review page. For example, as of now I can't tell if that is Section I.A or II.A or something else.

**Comment by jehlers** [comment]
Is this the same as #202? Or is this the implementation of #202?

**Comment by donjo** [comment]
I'd say this is a less detailed version of #202. I'll close this one out.
