### ISSUE TITLE
Mobile view for write/read tabs

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#145]
Right now, mobile users see

<img width="381" alt="screen shot 2016-04-13 at 4 49 52 pm" src="https://cloud.githubusercontent.com/assets/326918/14508928/d57f4dd2-0197-11e6-8884-99d1fa821b4f.png">

Clearly not ideal. Tagging with design for now, though if there are quick implementation fixes, let's do those now.

**Comment by jehlers** [comment]
#### Desktop

![desktop](https://cloud.githubusercontent.com/assets/4267825/14644096/db3120ee-061e-11e6-830b-7c259d858c96.png)

#### Tablet

Tabs loose some extra words to just read as "Read" and "Write," but still live to the right of the wayfinding header.

![tablet](https://cloud.githubusercontent.com/assets/4267825/14644104/e0bf952c-061e-11e6-992e-23221bdf3640.png)

#### Mobile

"Actions:" drops and the tabs use the full width of the phone screen underneath the wayfinding header.

![mobile](https://cloud.githubusercontent.com/assets/4267825/14644115/ea16bdee-061e-11e6-9ffd-1a9511e9cfc3.png)

Thoughts?

**Comment by jehlers** [comment]
Adding some designs for the global menu:

![screen shot 2016-04-19 at 11 29 49 am](https://cloud.githubusercontent.com/assets/4267825/14645065/40c0cb64-0622-11e6-8598-010a33988118.png)

**Comment by jehlers** [comment]
Global menu choice: An adjustment to 1 above. The text is better for mobile and adding the strokes below helps to keep plenty of room for fingers to touch the links.

![screen shot 2016-04-19 at 11 44 03 am](https://cloud.githubusercontent.com/assets/4267825/14645551/1c892d20-0624-11e6-85d0-f8c4d40cd38f.png)

**Comment by jehlers** [comment]
@xtine Do you need anything else from me?

**Comment by xtine** [comment]
@jehlers: not at the moment, once I get all of mobile styled up to these designs I'll just have you look over if there's anything you'd like to change then.

**Comment by jehlers** [comment]
@xtine Let me know when you want me to look over stuff! This is probably a next sprint task right?

**Comment by xtine** [comment]
@jehlers: yeah let's do it next sprint since some things have changed and I'll need to make another pass at updating mobile layout end of this sprint / beginning of next

**Comment by donjo** [comment]
This was all done in the latest mobile styles PR right?
