### ISSUE TITLE
Drawer stoke consistency

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#152]
Just noticed a color and weight difference of the stroke when the left drawer is closed:

![screen shot 2016-04-15 at 2 17 01 pm](https://cloud.githubusercontent.com/assets/4267825/14571089/7abe96a8-0315-11e6-8464-64ca9e695464.png)

It looks like the condensed tabs only have a 1px right stroke and then there is a color shift below it left over from the ON tab. Here's the normal open version:

![screen shot 2016-04-15 at 2 17 08 pm](https://cloud.githubusercontent.com/assets/4267825/14571133/a1a67ea2-0315-11e6-9d2c-39937a1abbdc.png)

Even here, there's a different color above the line where the subheader starts. 

Can we keep this color and weight consistently one color and size? Here's the the CFPB versions:

![screen shot 2016-04-15 at 2 21 30 pm](https://cloud.githubusercontent.com/assets/4267825/14571166/bf39ad9a-0315-11e6-9744-70fc08d25a29.png)

![screen shot 2016-04-15 at 2 21 36 pm](https://cloud.githubusercontent.com/assets/4267825/14571169/c1136a84-0315-11e6-88ff-ee9b8ce443b2.png)

**Comment by xtine** [comment]
Closing this issue because closed drawer strokes seem to be consistent for now:
<img width="65" alt="screen shot 2016-05-10 at 11 20 58 pm" src="https://cloud.githubusercontent.com/assets/24054/15171769/f8ee4740-1705-11e6-8bd7-cb74917ffcca.png">
