### ISSUE TITLE
Reviewing a comment fix **High priority, could cause user confusion**

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#167]
Can we not capitalize the section headers on the review page? I'm worried we will get some accidental capitalized letters in citations that shouldn't be. See the 3rd citation below.

Two updates: 

- [x] Sentence case (unless citations indicate otherwise) section headers. i.e. Section I.A
- [x] Adding the § in front of any regulation citation. i.e. § 478.21(a)(1)(i)
- [x] 2px rounded corners of the box to soften the area a little bit and make the download button look more like a button.

![screen shot 2016-04-20 at 2 22 37 pm](https://cloud.githubusercontent.com/assets/4267825/14685644/58a581b6-0703-11e6-9b30-44aefc2c50ad.png)

**Comment by cmc333333** [comment]
Eep. So one issue here is that this preview is inheriting styles from its surrounding HTML, including an `h4` rule which up-cases.

Would it be crazy to use an iframe here to a page that only has the styles present in the pdf generator? @xtine @vrajmohan @tadhg-ohiggins @jmcarp

**Comment by jehlers** [comment]
This may not be helpful, but they don't need to be an H4. The style of H5 would so that the uppercase is gone, but they are the same size.

**Comment by xtine** [comment]
Casing of the `<h4>` isn't a problem, since it's all wrapped in a `comment-review-wrapper` class.

Example:
<img width="830" alt="screen shot 2016-04-21 at 1 08 25 pm" src="https://cloud.githubusercontent.com/assets/24054/14722785/3fc37936-07c2-11e6-9040-3d464493623a.png">

**Comment by cmc333333** [comment]
@xtine, do you have local markup? Here's current demo:
<img width="1214" alt="screen shot 2016-04-21 at 5 06 43 pm" src="https://cloud.githubusercontent.com/assets/326918/14724347/8829d898-07e3-11e6-9517-c713d0b245bb.png">

**Comment by cmc333333** [comment]
Okay, you're screenshot is from eregs/regulations-site#274

The concern I'm raising is that this _isn't_ what the pdf will look like because it's being styled with CSS that won't be part of the pdf. I'll comment in that issue for specifics.

**Comment by cmc333333** [comment]
All the original checkboxes have been resolved and formatting issues are now in #307 so I'm closing.
