### ISSUE TITLE
Footnotes: Odd artifact when jumping back

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#181]
After clicking the jump link back to the text after reading a footnote, there's a pretty odd visual artifact:

<img width="628" alt="screen shot 2016-04-21 at 6 33 38 pm" src="https://cloud.githubusercontent.com/assets/326918/14726361/a6f232be-07ef-11e6-9395-963a99781c5d.png">

**Comment by xtine** [comment]
It's because of the css positioning hack to account for the fixed header. I removed link outlines for jump links so it won't show up.
