### ISSUE TITLE
“Top” (or landing page) of the rule pulls out useful meta data like contact info and comment period dates.

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#187]
Read Mode
[NEEDED] “Top” (or landing page) of the rule pulls out useful meta data like contact info and comment period dates. This page should also include the supporting docs from the docket and all the FR templated parts of the rule. [This is in progress?]

**Comment by jehlers** [comment]
This is in progress here: #106

**Comment by donjo** [comment]
Done?

**Comment by jehlers** [comment]
Does this include the design? If so, not done. If not, done. :)

**Comment by Journerdism** [comment]
Done!
