### ISSUE TITLE
Rule presented with proper type hierarchy and indentations.

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#188]
Read Mode
[ALMOST] Rule presented with proper type hierarchy and indentations. (Section titles start styled like an H2 so and the outline of header levels below it follow the H3, H4, … cascade.) [Still needs some polish and consistency]

**Comment by jehlers** [comment]
There are some type hierarchy issues throughout the tool:

![screen shot 2016-04-25 at 10 59 36 am](https://cloud.githubusercontent.com/assets/4267825/14788795/9b92c538-0ad7-11e6-9400-0c40032dcf9b.png)

We want the type hierarchy to follow this pattern. The H1 style should only be used on the homepage. But on the top of any section page, the § title or I, II, III title should start with an H2 style like (e) below.

![nc-typography](https://cloud.githubusercontent.com/assets/4267825/14788810/aaa20778-0ad7-11e6-8e4e-8627533fc733.png)

**Comment by jehlers** [comment]
Reopened because this hasn't been fixed yet.

**Comment by jehlers** [comment]
Here's an example:
![screen shot 2016-05-10 at 11 29 11 am](https://cloud.githubusercontent.com/assets/4267825/15152227/6f9a2828-16a2-11e6-8362-e877db19c1f5.png)

(V) should be styled like an H2 (not an H3) because it is the title of a page. And, I'm not sure why (A), and (1) are the same hierarchy level. (A) should be styles like an H3 under the page title, (V).

**Comment by donjo** [comment]
These changes were pulled in.

**Comment by jehlers** [comment]
Hey! This is looking great, but I found a couple of tiny issues. Let me know if we should re-open this issue or create a new one!

#### Paragraph indentation issues

<img width="203" alt="screen shot 2016-06-06 at 1 08 57 pm" src="https://cloud.githubusercontent.com/assets/4267825/15830728/f25bffde-2be7-11e6-90d2-0e7d62ffc73e.png">

B, and C in this section don't have indents below them. But D has the proper indentation. D is followed by a 1, 2, 3... Could this be the difference between the two types of paragraphs?

#### Lower down in the type heirarchy

Section I.E.2 Paragraph 8 has the new "comment headers" title. It seems very small. I think it should be the next level down after the 19px ALL CAPS semi bold. It should probably be 19px Sentence Case semibold.
