### ISSUE TITLE
Wayfinding header to follow the user’s scroll w/ the citation of where they are in the document

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#192]
[NEEDED] Wayfinding header to follow the user’s scroll w/ the citation of where they are in the document. [I think the URL part is working, but the section header is missing from the subheader]

**Comment by jehlers** [comment]
Same as ATF and CFPB:

![nav-wayfinding](https://cloud.githubusercontent.com/assets/4267825/14788646/e7869150-0ad6-11e6-843d-7bb767b8e57a.gif)

![nav-wayfinding-1](https://cloud.githubusercontent.com/assets/4267825/14788655/f152c0b4-0ad6-11e6-95c6-ee74e85de8c8.gif)

**Comment by jmcarp** [comment]
It would be helpful (for me, anyway) to work through some examples on this. I'm not clear on exactly what should appear in the subpart and section areas--do we have a concept of subparts for preambles, for example? So to be specific, what should show up in each of the two areas for a given preamble section and cfr change section?

cc @jehlers @cmc333333

**Comment by jehlers** [comment]
@jmcarp 

For the preamble, I think you're right that there is no subpart. So we should drop that part of the wayfinding and just have "Section III.A...." scroll through as you go.

For the CFR changes, we should include the subpart that each section would be in so it would match the design above: "Subpart FF   |   § 264.21(a)(1)..." 

Does that make sense? Did that answer your question?

**Comment by jehlers** [comment]
A side goal is to follow whatever citation a lawyer would use. Hence the use of parentheses in "§ 264.21(a)(1)." So I can double check this tomorrow, but I'm pretty sure the normal citation for the preamble would be dots/periods.

**Comment by jmcarp** [comment]
Sounds like we can use the `human_label` field for the section label, which would look like "Section I.B Paragraph 5.2" for preambles. Is that all right?

Also, @cmc333333: does the cfr changes data include subpart information?

**Comment by cmc333333** [comment]
+1 to using `human_label`. If we used it consistently, we'd be able to close 18F/atf-eregs#259 as well.

The cfr changes will include subpart information soon, we just don't have an example of it yet. At the moment, there is some [nasty](https://github.com/eregs/regulations-site/blob/master/regulations/static/regulations/js/source/views/drawer/toc-view.js#L48-L60) logic which walks the ToC (within JS) to determine the Subpart info. Ideally it'd be available to the HTMLBuilders, but I don't believe it is ATM.

**Comment by cmc333333** [comment]
This has been implemented; I know @jehlers mentioned some tweaks, but let's close this and open another issue if they are important.
