### ISSUE TITLE
The user can WYSIWYG edit their text in the browser

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#200]
Write mode
The user can WYSIWYG edit their text in the browser.  [It works but we should have it sit somewhere instead of only appear when the user highlights text (our user base can’t be expected to all be very tech savvy).]

**Comment by jehlers** [comment]
I noticed today that with our current editor, the italics always looks bold and italic. And when you try to make something bold and italic, the italic isn't actually visible.

**Comment by cmc333333** [comment]
#226 resolved the italic/bold issue; looking at the placement of icons now.
