### ISSUE TITLE
They should also ALWAYS see a header with the section number that matches what they will see when the comment is saved

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#203]
Write mode
[ALMOST] They should also ALWAYS see a header with the section number that matches what they will see when the comment is saved. [Not sure the header is there, and this excerpt doesn’t always show up]

**Comment by jehlers** [comment]
Related to #202

We want each excerpt to have a header that matches the section title the user will see when they save their comment and it is added to the right sidebar list of pending comments.

![screen shot 2016-04-25 at 11 05 29 am](https://cloud.githubusercontent.com/assets/4267825/14788411/b1948094-0ad5-11e6-94af-4302cf192eac.png)
