### ISSUE TITLE
The user can enter their name and organization info if they want

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#210]
[ALMOST] The user can enter their name and organization info if they want.

**Comment by jehlers** [comment]
#### If the user is submitting on behalf of themselves:

![updated review page myself](https://cloud.githubusercontent.com/assets/4267825/14787749/d9df2c6e-0ad2-11e6-8863-f0cb3e82bd27.png)

#### If the user is submitting on behalf of an organization:

![updated review page organization](https://cloud.githubusercontent.com/assets/4267825/14787764/ecb73f84-0ad2-11e6-9fec-2432cc960280.png)

#### If the user is submitting on behalf of a government agency:

![updated review page government agency](https://cloud.githubusercontent.com/assets/4267825/14787771/f0f0e2da-0ad2-11e6-9d51-ded76afedd6e.png)

**Comment by jmcarp** [comment]
The functionality for this issue is done. Styling is not, but we can track that in https://github.com/eregs/notice-and-comment/issues/246.
