### ISSUE TITLE
All the disclaimer text is on the page somewhere

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#211]
[NEEDED] All the disclaimer text is on the page somewhere.

**Comment by jehlers** [comment]
#### Collapsed disclaimer

![updated review page myself](https://cloud.githubusercontent.com/assets/4267825/14787705/9d2a59a6-0ad2-11e6-9fd9-c7da9151b57e.png)

#### Expanded disclaimer

Each paragraph can be expanded one at a time, but here is what it would look like if all of the text was fully expanded.

![updated review page fully expanded disclaimer](https://cloud.githubusercontent.com/assets/4267825/14787717/ada12120-0ad2-11e6-969a-17f5506b4227.png)
