### ISSUE TITLE
Page appears when the user clicks “submit”

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#212]
[NEEDED] Page appears when the user clicks “submit.”

**Comment by jehlers** [comment]
Designs here #62, but I'll repost:

#### Success but waiting

![success - pending tracking number](https://cloud.githubusercontent.com/assets/4267825/14787565/ec8d542c-0ad1-11e6-83a4-58f66f9077c5.png)

#### Success, here's the tracking number

![success copy](https://cloud.githubusercontent.com/assets/4267825/14787579/fca36e3c-0ad1-11e6-99d3-42d8b2ebc36d.png)

#### Our system failed

![fail](https://cloud.githubusercontent.com/assets/4267825/14787592/0a165430-0ad2-11e6-9d7c-263d800d52a5.png)

**Comment by jehlers** [comment]
Did we create another issue for styling this page? Can someone connect it here?

**Comment by jmcarp** [comment]
Here's the style issue: https://github.com/eregs/notice-and-comment/issues/238
