### ISSUE TITLE
Tracking number loads when we get it

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#213]
[NEEDED] Tracking number loads when we get it. Appropriate copy about why it may be taking a while shows up after a certain amount of time.

**Comment by jehlers** [comment]
Once we get the tracking number we should switch this out for the success message + the tracking number. Here's the waiting message: 

![success - pending tracking number](https://cloud.githubusercontent.com/assets/4267825/14787513/acbbaa24-0ad1-11e6-8b89-2d933f400cfd.png)
