### ISSUE TITLE
Embedded math

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#22]
The EPA proposed rule contains several equations. We need to figure out how these will be represented in the XML, parse them, and display them. Would it make sense to remove sub/super scripts from the formatting layer and instead have a math layer?

**Comment by grapesmoker** [comment]
MathML would seem to be the natural choice.

**Comment by vrajmohan** [comment]
MathML support appears to be very low - http://caniuse.com/#feat=mathml.

For the MVP, wouldn't creating SVGs using something like https://www.mathjax.org/ be adequate?

**Comment by cmc333333** [comment]
Let's figure out how the data gets to us before figuring out how to render it. It's very possible that all of the equations are rendered via images at the moment.

**Comment by ascott1** [comment]
Sorry for ignoring @cmc333333's comment above, but I would recommend [KaTeX](https://khan.github.io/KaTeX/) for rendering on the client.

I suspect his hunch is correct though and that these will often be provided as images.

**Comment by cmc333333** [comment]
Looks like either `GPH` or `MATH` tags are used along with an image. I don't think we'll need to worry about client-side rendering.
