### ISSUE TITLE
Days countdown on the top of the preamble turns RED and the word “closes” becomes “closed"

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#220]
[NEEDED] Days countdown on the top of the preamble turns RED and the word “closes” becomes “closed.”

**Comment by jehlers** [comment]
Part of #183

**Comment by jehlers** [comment]
#### Open

Days countdown and background is green: #2E8540 

![preamble introduction supporting docs](https://cloud.githubusercontent.com/assets/4267825/14787019/a01128e6-0acf-11e6-88d7-a9657f3dbc70.png)

#### Closed

Days are at 0; "closes" changes to "closed"; and background is red: #CD2026

![preamble introduction when comment period is closed](https://cloud.githubusercontent.com/assets/4267825/14787048/c6a47008-0acf-11e6-8c9e-b12726932bf0.png)
