### ISSUE TITLE
Review page responsive layout

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#225]
Similar to the read mode text, if the browser is wider, the text should have more room to spread out making it easier to read and so the edit links are always close to the text.

![screen shot 2016-04-25 at 11 00 15 am](https://cloud.githubusercontent.com/assets/4267825/14788436/ceffeb32-0ad5-11e6-8e4f-45fff36bb734.png)

**Comment by donjo** [comment]
Are you thinking full width and the edit on the same level as the section title or ~75% width and edit lined up with the paragraph text? 

![screen shot 2016-04-25 at 10 45 55 am](https://cloud.githubusercontent.com/assets/776987/14789626/05280292-0ad3-11e6-9476-5c8af5674b9f.png)
![screen shot 2016-04-25 at 10 44 37 am](https://cloud.githubusercontent.com/assets/776987/14789627/0528d352-0ad3-11e6-88d2-926b1f5a78cf.png)

**Comment by jehlers** [comment]
I was thinking the first image you sent over. Matching the layout in read mode the allows the text to always fill the width of the main content section and the link to write or edit is always in the right sidebar.
