### ISSUE TITLE
Client-side validation of attachment count

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#235]
Users should only be allowed to upload nine files (the tenth is the comment pdf that we create). We could disable the attachment interface when a user already has nine files uploaded, or allow users to upload >9 files but prevent them from submitting on the review screen until enough attachments are deleted. At the moment, this doesn't exactly break, since we're also validating the number of attachments server-side, but upload-happy users will get a failure screen and have to navigate back a few screens to fix their submissions.

**Comment by jmcarp** [comment]
Forgot to cc @jehlers @donjo

**Comment by jehlers** [comment]
Working on this shortly. We discussed setting user expectations by including a countdown of sorts on the write mode pages so the user knows they only have 9 attachments to work with from the start.

**Comment by jmcarp** [comment]
@jehlers: if we're settled on a general plan of showing a count of remaining attachments available and disabling attachments when the limit is reached, I can implement the behavior now, and then we can style and update content later on. Does that sound right, or should I hold off for now?

**Comment by jehlers** [comment]
That works @jmcarp! I can take this task on next if thats helpful.

**Comment by jehlers** [comment]
Some initial ideas:

#### Option 1
<img width="557" alt="screen shot 2016-04-29 at 4 52 17 pm" src="https://cloud.githubusercontent.com/assets/4267825/14929304/d7b3b4f4-0e2a-11e6-964b-a2b13d636613.png">

#### Option 2
<img width="556" alt="screen shot 2016-04-29 at 4 52 26 pm" src="https://cloud.githubusercontent.com/assets/4267825/14929314/e2b077ac-0e2a-11e6-973d-b3fbf6a1ec18.png">

This is closely related to #139

**Comment by donjo** [comment]
I think I lean more towards option 2 but my main concern is people understanding that this is a comment-wide limit and not just limited to that one response. I've been trying to think of a better way to word that but can't think of anything. Maybe just adding "total" as in "You've uploaded 2 total attachments"

**Comment by jehlers** [comment]
I like that idea @donjo. I'm also relying on the fact that people will see that number creep up as they upload different attachments to different comments.
