### ISSUE TITLE
Design message for disabled write mode when comment period is closed

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#236]
Allow the write tab to be clicked on, but replace write mode with a message that explains the comment period is over and sends users to the docket folder with all the comments (will design this sprint)

Part of #183

**Comment by jehlers** [comment]
Here are a few options:

#### 1 - Just text

![write mode when the comment period is closed](https://cloud.githubusercontent.com/assets/4267825/15052961/4a544a3a-12ce-11e6-88b5-1a77c8105f28.png)

#### 2 - Button

![write mode when the comment period is closed copy](https://cloud.githubusercontent.com/assets/4267825/15052977/50bcdd60-12ce-11e6-99d8-c0af214ad1f2.png)

#### 3 - Alert warning

![write mode when the comment period is closed copy 2](https://cloud.githubusercontent.com/assets/4267825/15052989/5e546f56-12ce-11e6-8a34-0b6d5a37e7bd.png)

#### 4 - Alert informational

![write mode when the comment period is closed copy 3](https://cloud.githubusercontent.com/assets/4267825/15052995/654fc08a-12ce-11e6-939d-96b2eb9db1d3.png)

**Comment by vrajmohan** [comment]
I like 4 - Alert informational with a couple of changes:
1. Link instead of button for viewing comments (like Option 1).
2. Closed date in the highlighted alert itself.

**Comment by jehlers** [comment]
A couple more options based on the feedback above:

#### Date outside the alert

![write mode when the comment period is closed](https://cloud.githubusercontent.com/assets/4267825/15127270/e70ab106-1603-11e6-8676-cecbdeb342cc.png)

#### Date inside the alert + slightly different copy

![write mode when the comment period is closed copy](https://cloud.githubusercontent.com/assets/4267825/15127284/f408b7fe-1603-11e6-9eb3-2c1048b41e1c.png)

Thoughts?

**Comment by vrajmohan** [comment]
I like Option 2, but without the _Sorry_. I have a problem when something that is automated says that it is _Sorry_.

**Comment by donjo** [comment]
I like option 1, mostly because "Comment period closed" all fits on one line.

**Comment by jehlers** [comment]
How about we meet in the middle?! And add a "back" button?

![write mode when the comment period is closed copy 2](https://cloud.githubusercontent.com/assets/4267825/15128554/6e1ff3b2-160a-11e6-89d3-78ef8ae7d57f.png)
