### ISSUE TITLE
Style comment confirm page

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#238]
The confirmation page has (most of) the behavior and content from the designs, but still needs to be styled. Paging @xtine and @donjo.

**Comment by donjo** [comment]
@jehlers could you post the final designs for this in the issue? I can pick this one up.

**Comment by jehlers** [comment]
Yep! Here they are:

#### Success but pending tracking number
![success - pending tracking number](https://cloud.githubusercontent.com/assets/4267825/14920872/599421b2-0dfd-11e6-8a90-7307b44c050d.png)

#### Success with tracking number
![success copy](https://cloud.githubusercontent.com/assets/4267825/14920881/6128e8fe-0dfd-11e6-92f4-c287cb005bbf.png)

#### Fail
![fail](https://cloud.githubusercontent.com/assets/4267825/14920887/668cbec4-0dfd-11e6-8340-e8a412591129.png)

**Comment by donjo** [comment]
Closing this since the remaining task is broken out in #342
