### ISSUE TITLE
Comment validation

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#24]
* Limit attachment count
    * Should limits be per-comment or total?
    * Will text-based comments be submitted as a file or as text? If a file, users can only attach nine additional files.
* Limit attachment size
* Disallow empty comments
* Potentially limit comment length

Note: all of the above should be checked server-side at minimum, and probably client-side as well.

**Comment by vrajmohan** [comment]
Adding notes based on regs.gov behavior:
1. Attachment with extension outside accepted extensions results in stack trace.
2. Attachment with size > 10M results in stack trace.
3. 4+ attachments of 9.2MB each results in:
```
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
```

**Comment by jmcarp** [comment]
Can we tell whether the error is related to the number of files versus the size of the files? Do we get the same error with the attachments in a tarball?

**Comment by vrajmohan** [comment]
I am going to establish more data points. tarballs will not work as they only accept the following "types": "bmp", "doc", "xls", "pdf", "gif", "htm", "html", "jpg", "jpeg", "png", "ppt", "rtf", "sgml", "tiff", "tif", "txt", "wpd", "xml", "docx", "xlsx", "pptx".

**Comment by vrajmohan** [comment]
The validations identified in this issue have been implemented.
