### ISSUE TITLE
Style additional info and disclaimers on review page

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#246]
We now have overridable additional info and disclaimer sections on the comment review page, but since I implemented them, they don't look good. We need to style the tabs for the commenter groups ("Myself", "An organization", "A government agency"), the form elements, and the disclaimer text and toggles. Right now, they look like this:

<img width="645" alt="screen shot 2016-04-29 at 2 55 43 pm" src="https://cloud.githubusercontent.com/assets/1633460/14926874/77b75898-0e1c-11e6-9504-252dfae9df41.png">

<img width="555" alt="screen shot 2016-04-29 at 3 09 57 pm" src="https://cloud.githubusercontent.com/assets/1633460/14926878/7d509f1c-0e1c-11e6-8fcd-b94a422e4c8a.png">

cc @xtine @donjo

**Comment by jehlers** [comment]
Adding the designs for easy reference. :)

The toggle should default to "Myself" and show no collection inputs.

#### Organization type

![ecb73f84-0ad2-11e6-9fec-2432cc960280](https://cloud.githubusercontent.com/assets/4267825/14928679/6d99f81a-0e27-11e6-9d25-549224580408.png)

#### Government agency

![f0f0e2da-0ad2-11e6-9d51-ded76afedd6e](https://cloud.githubusercontent.com/assets/4267825/14928689/777dcf14-0e27-11e6-90b8-33947858dc41.png)

**Comment by donjo** [comment]
@jehlers do you have an example of the expanded "show more"? I can't remember if it's the same text style as the unexpanded and if there was any additional spacing or not.

**Comment by jehlers** [comment]
Yep! Here you go! Hidden text is 12px but keeps the space between the bullet points when opened. :)

![review 02 copy 15](https://cloud.githubusercontent.com/assets/4267825/15129165/f416bf0c-160d-11e6-8f4a-680f26dc2083.png)

**Comment by jehlers** [comment]
If additional space is needed once it's implemented, that's fine with me. :)
