### ISSUE TITLE
ToC color issue

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#248]
Note that the right border switches from a dark grey to a lighter version

<img width="64" alt="screen shot 2016-05-02 at 12 43 33 pm" src="https://cloud.githubusercontent.com/assets/326918/14960629/924301aa-1063-11e6-99e6-fd26c58f5411.png">

**Comment by donjo** [comment]
#245 should cover that

**Comment by cmc333333** [comment]
Excellent
