### ISSUE TITLE
Design / implement success / failure states

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#25]
As of https://github.com/18F/regulations-site/pull/128, nothing happens when comment submission succeeds or fails--the callbacks are stubs that literally don't do anything:

```javascript
...
submitSuccess: function(resp) {
  // TODO(jmcarp) Figure out desired behavior
},
submitError: function() {
  // TODO(jmcarp) Figure out desired behavior
}
...
```

Minimally, we should show a message (and probably clear out pending comments) on success, and show a warning on error. Likewise for success / failure on file uploads and saving per-section comments.

**Comment by Journerdism** [comment]
DONE
