### ISSUE TITLE
Add a print button, check print.css

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#253]
Based on usability testing feedback, add a print button and check the print.css to make sure it looks good for the American people

**Comment by cmc333333** [comment]
We haven't spoken about this in a while -- I'm guessing we're checking the CSS but that we're not adding a new button, yes?

**Comment by donjo** [comment]
That sounds like a good plan to me.

On Thu, Jun 2, 2016 at 5:35 PM, CM Lubinski <notifications@github.com>
wrote:

> We haven't spoken about this in a while -- I'm guessing we're checking the
> CSS but that we're not adding a new button, yes?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eregs/notice-and-comment/issues/253#issuecomment-223442977>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAvbG67SFxcHFXwM-ndugw415yv-YC-zks5qH1q0gaJpZM4IWWSX>
> .
>



-- 
John Donmoyer
18F – User Experience Designer
312-869-0339

**Comment by cmc333333** [comment]
eregs/regulations-site#429 did a lot of good here. Other bits that we probably want to look at:

* [ ] Preamble intro page contains jump links and a countdown which probably don't make sense when printing
* [ ] CFR change section includes "Show more context", which obviously can't be clicked in print. Probably just want to hide that text, leaving the stars

**Comment by donjo** [comment]
eregs/regulations-site#429 resolved the site-wide print issues and we elected to not add a print button to the page as users can use the print functionality in their browsers.

I'm going to create a new issue for page-specifc print.css refinement covering the items CM mentioned and close this one out.
