### ISSUE TITLE
Read mode should look "off" when in write mode

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#256]
When clicking out of read mode into write mode, the read tab looks like this:

![screen shot 2016-05-03 at 11 43 41 am](https://cloud.githubusercontent.com/assets/4267825/15117812/4b508564-15d7-11e6-918a-ee8f8e980b6b.png)

It should match the all gray write mode tab when the user is not using it:

![screen shot 2016-05-09 at 11 19 35 am](https://cloud.githubusercontent.com/assets/4267825/15117929/eade2032-15d7-11e6-8f94-fc32b2e6a073.png)

**Comment by Journerdism** [comment]
Closed!
