### ISSUE TITLE
"Read the Proposal" link wrong in CFR changes

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#273]
Appears to be pointing to the preamble instead
<img width="976" alt="screen shot 2016-05-12 at 1 51 25 pm" src="https://cloud.githubusercontent.com/assets/326918/15224677/ba08e35c-1848-11e6-89f5-f71d66f72b5d.png">

**Comment by jmcarp** [comment]
Do we expect this to link to the current section?

**Comment by cmc333333** [comment]
I see what you are saying -- the "Read the proposal" link always points to the intro, regardless of which section (or mode) you're in. I think the expectation is to link to the current section, yes, but @jehlers @donjo correct me if I'm wrong.
