### ISSUE TITLE
Homepage CSS tweaks

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#277]
A few _very_ small spacing/font/CSS tweaks for the homepage listed here:

**Hero space**
The EPA/proposal box should not be flush with the bottom of the image. There's a few things that will help us get there:
- [x] "Read, understand, and comment on new proposed laws." should be H1 (44px instead of 40px)
- [x] 20-30px more visual space above "Read, understand, ..."
- [x] "We request..." should be H2 (34px)
- [x] 10px more visual space between the two lines of text

The EPA/proposal box itself:
- [x] Round all 4 corners of the box - 2px radius (top two of the white part, bottom two of the blue button)
- [x] Stroke separating the comment date and the title should be #9BDAF1 (to match the background color)
- [x] Bottom gray stroke/border of the white part of the box should not be there so that the white runs flush with the blue button.
- [x] Title of the proposal should be the size of an H3 (24px) but Source Sans Pro Light.

**Even as an individual, you can substantially change a regulation by writing a helpful comment on a proposed rule.**
- [x] Should be the size of an H2 (34px)

**Read and write with ease**
- [x] Can we have a full 30px gutter between the images and the text to the right of it. It visually looks like 22px now. 

**About this tool**
- [x] Spacing below the title "About this tool" should match the spacing under the other two headers above it.

**Comment by jehlers** [comment]
One more thing that @donjo and I talked about eariler this week. We want to update the image and add a blue background so that on larger displays we can center the photo.

- [ ] Use the following photo, center it on the page, and the background should be #b3e0eb so that it fades into it. :) 

![hero-gradient](https://cloud.githubusercontent.com/assets/4267825/15229099/80179d7c-185d-11e6-90f8-5e09de082a5f.jpg)

**Comment by jehlers** [comment]
Homepage looks good! Only thing missing (that I know @xtine is working on) is putting the text inside the expandable under "Other ways to read and comment." 🎉

**Comment by donjo** [comment]
Is this one all done now?

**Comment by jehlers** [comment]
Yep! Everything looks great on eregsnc-demo, I assume it will all move over to epa-notice soon?

**Comment by Journerdism** [comment]
YESSS CLOSED!
