### ISSUE TITLE
Schematics/diagrams on README are broken image links

### ISSUE THREAD

**Issue by toolness** [eregs/notice-and-comment#283]
:disappointed: 

![broken-images](https://cloud.githubusercontent.com/assets/124687/15246018/05ba5b5c-18d8-11e6-87b2-06a7f15b9f00.png)

It seems they are pointing to a directory in the repository called `docs` that no longer exists?

**Comment by cmc333333** [comment]
See http://atf-eregs.readthedocs.org/ ; notice-and-comment is nearly identical

**Comment by toolness** [comment]
Thanks! Do you think the broken images should be fixed to point at the images at atf-eregs, or should they be removed entirely?

**Comment by cmc333333** [comment]
I think we'll rework the README to be a read-the-docs site similar to atf-eregs once we get to a steady state

**Comment by cmc333333** [comment]
This is up to date now
