### ISSUE TITLE
Other files in the Docket

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#295]

**Comment by cmc333333** [comment]
To flesh this out a bit:
Design at #106

For example, for this notice: https://www.federalregister.gov/articles/2016/02/29/2016-02749/addition-of-a-subsurface-intrusion-component-to-the-hazard-ranking-system
We'd need to pull out a docket id: https://www.regulations.gov/#!docketDetail;D=EPA-HQ-SFUND-2010-1086
And pull in all "Supporting" and "Other" documents:
* https://api.data.gov/regulations/v3/documents.json?api_key=DEMO_KEY&dct=SR&dktid=EPA-HQ-SFUND-2010-1086
* https://api.data.gov/regulations/v3/documents.json?api_key=DEMO_KEY&dct=O&dktid=EPA-HQ-SFUND-2010-1086

The UI should only show the _first_ (by creation date ASC) 3 documents and then link to https://www.regulations.gov/#!docketBrowser;rpp=25;po=0;dct=SR%252BO;D=EPA-HQ-SFUND-2010-1086 for "more"

**Comment by cmc333333** [comment]
Relevant PRs merged, good to go
