### ISSUE TITLE
Subpart and ToC navigation scrolls to slightly wrong position for some subparts

### ISSUE THREAD

**Issue by tadhg-ohiggins** [eregs/notice-and-comment#296]
For example,
/preamble/0000_0000/cfr_changes/264-1300#0000_0000-cfr-264-1300 and /preamble/0000_0000/cfr_changes/265-1311#0000_0000-cfr-265-1311

both work but

/preamble/0000_0000/cfr_changes/265-1310#265-1310

scrolls slightly too far down the page and hides the subpart navigation.

**Comment by donjo** [comment]
Fixed in eregs/regulations-site#365
