### ISSUE TITLE
Header and subheader CSS tweaks

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#309]
Here are a couple of small CSS polish to the header and subheader.

#### Header

- [x] Take out "partnership between." @donjo and I have talked about this. That adds some clutter up around the tabs, we should keep that language in the footer on the homepage, but let's clean it up in the header. Especially since we are also taking about "About" in #297. 
 
![screen shot 2016-05-18 at 12 10 13 pm](https://cloud.githubusercontent.com/assets/4267825/15366322/c6b5c8b0-1cf1-11e6-90c9-a78321b76aef.png)

#### Subheader

**Wayfinding**
- [x] The wayfinding citation shouldn't be italicized; it feels "shaky" that way, which we don't want. Can it just be Source Sans Pro Regular?
- [x] Also, it feels indented from the main content area. Can we line it up (left justify) with title on the page, or in the case below the "I. The first section." _This may be related to the missing "subpart" part of this header?_

![screen shot 2016-05-18 at 12 09 45 pm](https://cloud.githubusercontent.com/assets/4267825/15366384/16d6ddca-1cf2-11e6-8fc2-d536d79f20a1.png)

**Subheader size**
- [ ] "Actions:" really points this part out because it feels squished. Can we either vertically center all the text "Section XX," "Read the proposal," and "Write a comment" in the subheader? Or we could make the subheader a few pixels taller so the bottom padding matches the top padding. Either way works for me.

**Comment by donjo** [comment]
we may not need to remove the "Partnership by" text anymore since the About page is gone and no longer creating some weird whitespace by having two large elements (the icons and the About text) straddling a smaller font. Here are both versions to compare. 

![screen shot 2016-05-18 at 11 21 45 am](https://cloud.githubusercontent.com/assets/776987/15366614/c43286f2-1cea-11e6-8af2-19cc6fac8409.png)
![screen shot 2016-05-18 at 11 21 31 am](https://cloud.githubusercontent.com/assets/776987/15366615/c43bd702-1cea-11e6-84e4-52b1117abaf4.png)

**Comment by jehlers** [comment]
One more thing! We will want to FR citation where the regulation CFR citation normally lives:

![screen shot 2016-05-18 at 1 23 19 pm](https://cloud.githubusercontent.com/assets/4267825/15368446/cf6382a4-1cfb-11e6-9ffd-30d71fe1fa62.png)

This may be a data thing? @cmc333333 @tadhg-ohiggins

**Comment by jehlers** [comment]
@donjo I could go either way on that text. What do you think?

**Comment by cmc333333** [comment]
eregs/notice-and-comment#374 for citation

**Comment by donjo** [comment]
Closing this out since I just merged in the citation piece. Re: the subheader size point, we decided to punt on that given the scope of work necessary (there are a lot of moving pieces in that subheader)
