### ISSUE TITLE
Upload attachment not working in test enviornment

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#318]
The upload attachment doesn’t work in the test environment

**Comment by cmc333333** [comment]
Attachments seem to be working for me in both the production and demo sites. I went to add a comment, selected a (png) attachment, followed that through to the review page, could preview that attachment, and could submit the comment.

What's not working?

**Comment by Journerdism** [comment]
Internet explorer might be the issue

**Comment by cmc333333** [comment]
Problem appears to be with IE

**Comment by Journerdism** [comment]
:jinx:

**Comment by cmc333333** [comment]
Bill tries to click the "Upload Attachment" button and nothing happens.

**Comment by cmc333333** [comment]
The "Upload Attachment" button is triggering a form submit on IE
