### ISSUE TITLE
Section I.E. missing underlines on comment headers

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#323]
-        Getting back to the timing of the load of the final version of the proposed rule, Section I.E. is missing the underlines on each of the comment headers.

**Comment by cmc333333** [comment]
I'm not sure that the Federal Register allows underlines...

**Comment by cmc333333** [comment]
Bill says the underlines were added to match the third-level of the printed preamble (which generally prints with underlines). He's going to check back with FR about how this will be printed.

**Comment by Journerdism** [comment]
Not gonna do it. Pull into guidelines for the future!
