### ISSUE TITLE
Linking on EPA site (and text)

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#324]
Update this link (and text) https://www.epa.gov/dockets/where-send-comments-epa-dockets

**Comment by donjo** [comment]
Is this referring to the last link in this list on the homepage?

![screen shot 2016-06-01 at 12 36 45 pm](https://cloud.githubusercontent.com/assets/776987/15719431/89100fc0-27f5-11e6-9655-4cb2e498ecb2.png)

**Comment by jehlers** [comment]
Yes! That link is meant to be where the "Additional submission formats accepted by EPA" goes. :)
