### ISSUE TITLE
Content tweak on receipt page

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#325]
-        After submission, at the bottom of the receipt page, not sure if it’s a typo, but you have “part of the >General Services Administration”

**Comment by donjo** [comment]
seems to be fixed now

![screen shot 2016-06-01 at 12 25 43 pm](https://cloud.githubusercontent.com/assets/776987/15719107/0b93a666-27f4-11e6-9a4d-052238f2af1b.png)
