### ISSUE TITLE
No fields for Normal person?

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#327]
When submitting as a normal person, no fields come up for name or anything (Using Chrome on a mac):

![screen shot 2016-05-27 at 2 16 55 pm](https://cloud.githubusercontent.com/assets/406607/15617192/c2423086-2415-11e6-8560-4c16f845407b.png)

**Comment by cmc333333** [comment]
This is correct; there are no additional questions for individuals.

**Comment by Journerdism** [comment]
That's weird.

**Comment by Journerdism** [comment]
Add a line of text that says "we don't accept names" or something

**Comment by donjo** [comment]
what do you think of this style?

[image: Inline image 1][image: Inline image 2]

On Fri, May 27, 2016 at 1:20 PM, CM Lubinski <notifications@github.com>
wrote:

> This is correct; there are no additional questions for individuals.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eregs/notice-and-comment/issues/327#issuecomment-222218270>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAvbG9VHzLWbOBYuPx7PFjFOKCvzamZwks5qFzXRgaJpZM4Iovvx>
> .
>



-- 
John Donmoyer
18F – User Experience Designer
312-869-0339

**Comment by donjo** [comment]
what do you think about this option?

![screen shot 2016-05-27 at 2 41 40 pm](https://cloud.githubusercontent.com/assets/776987/15619562/97ba50dc-241a-11e6-8782-ee9077ee764b.png)
![screen shot 2016-05-27 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/776987/15619563/97bca026-241a-11e6-975a-0ffb8309b891.png)

**Comment by donjo** [comment]
Fixed in eregs/regulations-site#381
