### ISSUE TITLE
PDF files posting with 0 bytes

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#329]
Investigate issue surfaced in live test

**Comment by cmc333333** [comment]
The regular attachments are passing through but the comment pdf itself is zero bytes. It displays correctly for the user on our side but doesn't appear to make it to regs.gov.

Maybe we need to rewind the file pointer or similar?

**Comment by jmcarp** [comment]
@vrajmohan: looks like adding `comment_pdf.seek(0)` after calling `cache_pdf` will do it.

**Comment by vrajmohan** [comment]
Thanks, that looks like it.

**Comment by vrajmohan** [comment]
Verified that this is indeed fixed. Relevant tracking number: 1k0-8pxx-78sa
[comment (9).pdf](https://github.com/eregs/notice-and-comment/files/294381/comment.9.pdf)
