### ISSUE TITLE
Implement pre-pub state for the rule

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#334]
There are 5 main parts:
- [x] Homepage message
- [x] Hiding the XX FR XXXX citation in the global header
- [x] Updating the preamble introduction where we won't have information about the comment period
- [x] Disabling the comment links in the sidebar like when the comment period is closed
- [x] Showing a message/alert if the write mode tab is clicked (similar to the when the comment period is closed)

**Here's a design for the homepage during the pre-pub phase:**

![closed 1 copy](https://cloud.githubusercontent.com/assets/4267825/15620705/ec2f81aa-2429-11e6-8a13-4ef7030b812b.png)

**For the other parts of the tool that need to mention that the rule isn't yet published:**

- Preamble introduction that mentions the dates of the comment period: 
  - Can we hide the X days countdown?
  - Change the comment period date to say "The comment period is not open."
  - Change the published date to say "The rule is not yet published in the Federal Register."

<img width="992" alt="screen shot 2016-05-27 at 4 37 28 pm" src="https://cloud.githubusercontent.com/assets/4267825/15620631/567ee812-2429-11e6-9bae-11ae20c11d44.png">

- Let's follow the pattern we have for when the comment period is closed if someone clicks on the write mode tab:

![write mode when the comment period isn t open yet](https://cloud.githubusercontent.com/assets/4267825/15620759/430e6c52-242a-11e6-81b8-8acafde6512e.png)

**Comment by cmc333333** [comment]
@tadhg-ohiggins is handling the home page part

**Comment by cmc333333** [comment]
All merged
