### ISSUE TITLE
Style and implement table of contents 

### ISSUE THREAD

**Issue by donjo** [eregs/notice-and-comment#34]
The table of contents needs to be modified to accommodate the preamble format and fit the overall style of the eRegs N&C site. 

Here is a rough wireframe of what this may look like. 
![screen shot 2016-03-22 at 10 35 13 am](https://cloud.githubusercontent.com/assets/776987/13957272/d803bbc2-f019-11e5-9097-115eab9149da.png)

**Comment by jmcarp** [comment]
As far as I can tell, the table of contents for preambles is built directly from the node tree in the templates at https://github.com/18F/regulations-site/blob/master/regulations/templates/regulations/preamble-chrome.html#L27-L43. But regulation tables of contents are separate layers that come from -parser. Seems like we'd either want to add a layer to -parser for preamble tables of contents, or parameterize the depth of the table of contents we generate for preambles in -site. I don't remember preamble sections going deeper than two levels so far, but this might be specific to the proposals we've been looking at so far.

What do you all think @cmc333333 @vrajmohan @tadhg-ohiggins?

**Comment by cmc333333** [comment]
Preambles definitely go deeper than two levels for headers. You are correct that `preamble-chrome` just walks the preamble tree -- we've got a small tree and no data layers just yet. I'd be in favor of doing the ToC layer thing for consistency.

One big question here, @donjo : what happens when a user click on "2. Another Subsection here"? Do they see _just_ that subsection? Do they see that subsection but also everything in "B. Issuance of First" (i.e. using an anchor)? Do they see everything in "II. Background"? Or do they see the entire preamble?

**Comment by donjo** [comment]
I forget where we left off here but I believe we decided that for the 3rd level they would see it in the context of the level above it but anchored to that point in the page. The URL would change to reflect the part they're anchored to so they could copy/paste that into an email to a coworker.

@jehlers does that sound right to you?

Ultimately this is just what felt natural but I'd love to run some users tests on whatever we choose to see if users can still effectively find and link others to specific sections of the document.

**Comment by cmc333333** [comment]
Does this sound like what you want?

| level | example | url | (simplified) anchor |
| --- | --- | --- | --- |
| 1 | II. Background | /doc_id/II | N/A |
| 2 | B. Issuance of ... | /doc_id/II/B | N/A |
| 3 | 2. Another ... | /doc_id/II/B | 2 |
| 4 | a. No example | /doc_id/II/B | 2-a |

**Comment by donjo** [comment]
Yeah that sounds right. We may not choose to show level 4 in the ToC itself because of space concerns but would still want to be able to anchor to that. (How the user would discover that they can link to a level 4 item is to be determined)

**Comment by jehlers** [comment]
Yeah, that's all sounds right. I have been thinking about the levels like this:

**Preamble introduction**
- All "sections" before "SUPPLEMENTARY INFORMATION" can live on one page in this section hence:

![screen shot 2016-03-23 at 5 26 40 pm](https://cloud.githubusercontent.com/assets/4267825/14001464/64d6bc68-f11c-11e5-9156-188d1dc300da.png)

Then we start with the roman numerals sections:

**I. General Information**
- A. Does this.... ?
- B. Next section text...
- C. More more more
**II. Next big section like a sub-part**
- A. Does this.... ?
- B. Next section text...
- C. More more more

@donjo and I agree that we want the ability to show off one more section below the A, B, C level. Which in this proposal is a 1, 2, 3 level. We've talked about only having this level appear once a user is inside the A, B, C level. Meaning if I was in I.A the TOC would look like this:

**I. General Information**
- A. Does this.... ?
  - 1. Something
  - 2. Something 
  - 3. ....
- B. Next section text...
- C. More more more
**II. Next big section like a sub-part**
- A. Does this.... ?
- B. Next section text...
- C. More more more

I think the bigger question here is can someone click on the I, II, III level or just the A, B, C level?

**Comment by cmc333333** [comment]
> I think the bigger question here is can someone click on the I, II, III level or just the A, B, C level?

There are definitely paragraphs which only live in the I, II, III level (put differently, some of the top-level sections don't have sub-sections). We could create some sort of artificial "introduction" sub-section, if we really wanted to avoid allowing I, II, III to be clicked.
