### ISSUE TITLE
Wayfinding label position

### ISSUE THREAD

**Issue by xtine** [eregs/notice-and-comment#344]
Should the wayfinding label be aligned to the content? Currently there's extra space to the left.

![wayfinding-label-position](https://cloud.githubusercontent.com/assets/24054/15755406/81441fae-28b1-11e6-9082-f6b3dd1b629c.png)

**Comment by donjo** [comment]
Yes. I think that is happening because those sections don't belong to a subpart so normally it would look like `Subpart | Section III` so whoever takes this on, check to make sure the solution works on old eregs.

**Comment by xtine** [comment]
Okay, there's the `.preamble-sub-head` parent class so changes shouldn't affect old eregs.

**Comment by donjo** [comment]
Just realized that this issue was brought up in #309 so writing this here so I remember to close out that too when I review.
