### ISSUE TITLE
Confirmation screen CSS polish

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#353]
- [x] “Success!” should be styled like an H2 (34px, Source Sans Pro Semibold) and the check icon should be the same size 34px so it fits better with the text.
- [x] Green padding on the top and bottom of the Success and Thanks! text should be 20px each.
- [x] “download your submitted..” link should be 15px under “want to save a copy…” so that it lines up with the bottom of the PDF icon.
- [x] “Want to save a copy…” should be 30px of visual space below the green box.
- [x] 45px of visual space should be under “download your submitted pdf…” before the stroke. Same space should be above and below all strokes on this page to help space out the page.
- [x] "Your comment tracking number,” "What will happen to your comment,” and "You can give feedback on this tool” should be styled as an H3 (24px semibold) 
- [x] And then the two next level down headers "EPA will process it and in most cases will post it publicly” and "EPA will review eligible comments and will usually publish a final rule” should be styled as H4s (19px semibold all caps)
- [x] Is there a way to not let a period be on another line by itself?

![screen shot 2016-06-07 at 10 25 11 am](https://cloud.githubusercontent.com/assets/4267825/15861702/3109eff8-2c9b-11e6-856f-808eae33677c.png)

- [x] **HIGHEST PRIORITY:** We need to call out the comment tracking number visually so people know what to look for quickly. Can we style it like this:

![screen shot 2016-06-07 at 10 25 37 am](https://cloud.githubusercontent.com/assets/4267825/15861692/23cc437c-2c9b-11e6-9c5f-c067434558ee.png)

- [x] Similarly, while we are waiting for the comment tracking number, the box should be blue with a spinning icon. Can we also expand down the second box after 10 seconds of waiting?

![screen shot 2016-06-07 at 10 26 35 am](https://cloud.githubusercontent.com/assets/4267825/15861696/28f6f4e6-2c9b-11e6-8021-0ad7a9a09c45.png)

cc @xtine and @donjo

**Comment by donjo** [comment]
This was mostly wrapped up in #342. I didn't get to the part where the "if this is talking a long time" box appears after 10 seconds, right now it appears immediately. We can swing back around to that as a low priority thing if there is ever time.

**Comment by jehlers** [comment]
@donjo Is this live? If I check on it on my machine will I see the updates?
