### ISSUE TITLE
Review page CSS polish

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#355]
**HIGHEST PRIORITY**

- [ ] “ADDRESSES” in the last sentence of the expanded second bullet should be an internal link back to that part of the preamble introduction page.

**LOW**

- [ ] Should we add a header like “Final submission” before the disclaimer? Right now the bullets look too closely connected to the “I’m submitting on behalf of…” - @donjo What do you think?

**Comment by donjo** [comment]
For the second thing, are you talking about something like this? 

![screen shot 2016-06-17 at 12 32 59 pm](https://cloud.githubusercontent.com/assets/776987/16159321/beb37a24-3487-11e6-9324-8915f64c0100.png)

**Comment by donjo** [comment]
I think I like that idea but maybe a different term. Since this is to mirror "Include your information" it should probably describe the section below.

"Review terms and conditions"
"Review submission guidelines" 
"Agree to terms and conditions"

something like that?

**Comment by jehlers** [comment]
Yes, I think that helps @donjo! I agree with your suggestions too. Should it also include the concept of submission? 

"Review submission guidelines and submit" 
"Agree to terms and conditions to submit" 
(?)
