### ISSUE TITLE
Mobile menu links

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#369]
We need to set this to something other than "Org Name"

<img width="396" alt="screen shot 2016-06-09 at 10 10 35 am" src="https://cloud.githubusercontent.com/assets/326918/15932732/c286cf1a-2e2a-11e6-946e-0f493c4177c0.png">

**Comment by jehlers** [comment]
This is partially addressed in https://github.com/eregs/notice-and-comment/issues/356

Here's the expected behavior and design:

![d3ae7b34-2ca5-11e6-9b1f-c520361edf34](https://cloud.githubusercontent.com/assets/4267825/15939756/32289a30-2e47-11e6-928b-8a436ea46645.png)
