### ISSUE TITLE
Prettify attachment interface

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#37]
At the moment, attachments simply start uploading on select, and appear in a list once uploaded to S3. Users might expect a drag-and-drop interface, progress bar, uploads that can be canceled, and a prettier interface overall. I've used dropzonejs in the past and liked it, so that's where I'd start if we want uploads to be less barebones.

If this would be useful, I'd be down to implement. Pinging @xtine @jehlers @donjo for comment--is this something we should do? If so, should we do it soon?

**Comment by jehlers** [comment]
Looks like this :)

![screen shot 2016-04-25 at 4 22 45 pm](https://cloud.githubusercontent.com/assets/4267825/14797699/f44149fa-0b01-11e6-9589-e13b9f770f1a.png)
