### ISSUE TITLE
Parser: Django phase one

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#379]
This needs to be broken into smaller issues.

For this first sprint, we want to be able to have a web interface that triggers the shell scripts associated with the parser. We want to handle this asynchronously.

**Comment by tadhg-ohiggins** [comment]
Quick breakdown thoughts:

[] Basic Django site with the Django REST auth module working.
[] Information architecture/API structure outline/diagram for the parser site.
[] A running basic framework for celery/worker/Redis.
[] Web interface allows user to invoke parser via shell script.
