### ISSUE TITLE
Refine comment builder

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#38]
As of https://github.com/18F/regulations-site/pull/141, comments are assembled into markdown roughly like this:

```markdown
# 2016_02749/I
bob

## Attachments
* lob.txt

# 2016_02749/II/A
law
```

We'll likely want to refine this. A few outstanding questions (I'm sure I'm missing others):
* Is markdown an acceptable format?
* If so, should markdown be sent as text or as a file attachment?
* If not, should we convert to HTML, PDF, etc?

**Comment by jmcarp** [comment]
I looked into PDF conversion. It's not hard to do, but there's a complication: all the tools I've encountered that work well also come with serious system dependencies. Pandoc works well, but has to be installed outside of python, and also requires pdflatex. Weasyprint also produces good output but also requires cairo, pango, gdk-pixbuf, and lxml. We can probably get these to install on cloud.gov, but might have to jump through some hoops (e.g. using `apt-buildpack` as well as `python-buildpack`, using `buildpack-multi` for multi-buildpack support). Deploys could also be pretty slow, since we build all dependencies from scratch. There are also some node libraries that use phantomjs to render html to pdf, but then we're using node, or shelling out to phantomjs--and the output didn't look great locally.

I see that `wkhtmltopdf` includes pre-built binaries that are only 15mb, so we might be able to check those into the repo and call them directly from cloud.gov. I'll give it a shot.

Interested to hear feedback from @cmc333333 @vrajmohan @tadhg-ohiggins

**Comment by jmcarp** [comment]
Update: including the `wkhtmltopdf` binary with `cf push` works just fine. It also takes several seconds to run for a longer html document. Not an issue when we're running it in a celery worker, but not ideal for in-process.

**Comment by vrajmohan** [comment]
I don't have much to add except that I skimmed perhaps the same docs as you. Found projects build around ReportLab - the popular one appears to be https://xhtml2pdf-base.googlecode.com/hg/doc/xhtml2pdf-en.html. Bottom line, I'm OK with `wkhtmltopdf` if the performance issue can be fixed.

**Comment by jmcarp** [comment]
Interesting--the python lib behind reportlab, `xhtml2pdf`, is pip-installable (although it depends on pil, which can be a pain to install), and produces decent output. It's also a lot slower than `wkhtml2pdf` for bigger documents:

```
± wc longer.html
    1001   11880  103521 longer.html
```

```
± time xhtml2pdf longer.html
Converting longer.html to /Users/jmcarp/code/regulations-site/longer.pdf...
xhtml2pdf longer.html  2.52s user 0.14s system 18% cpu 14.456 total
```

```
± time wkhtmltopdf longer.html longer2.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
wkhtmltopdf longer.html longer2.pdf  1.27s user 0.13s system 54% cpu 2.566 total
```

Depending on what kind of caps we want to impose on comment sizes, making pdfs could take some time with either tool, and I don't want the app to get sluggish if we get hit with a lot of pdf export requests. But in the interest of making incremental progress, I think I'll send in a basic pull request with wkhtmltopdf, and we can revise from there--we can always add another app (microservices!) that just builds pdfs so that the main app doesn't get bogged down, or push pdf creation to the celery workers.

Sound reasonable @vrajmohan @cmc333333 @tadhg-ohiggins ?

**Comment by cmc333333** [comment]
Something else to consider: we may not need to convert to pdf for most preview/reviews. Since it looks like we need to render HTML before rendering a pdf, we can just display that in an iframe or similar without the pdf conversion.

**Comment by jmcarp** [comment]
@cmc333333: at the moment, the mocks expect a downloadable pdf preview. If we show html inline or in an iframe, then we don't have to worry about bogging down the app server with pdf exports, which is neat. If we go that way, though, the html preview is both (slightly) different from the final pdf output, and very similar to the markup above the "download preview" button here: https://cloud.githubusercontent.com/assets/4267825/14155045/ebfd4556-f68d-11e5-9e89-a350fbd7bee3.png.

**Comment by vrajmohan** [comment]
I also feel that it may be better to stick to plain HTML. The pdf option brings in a whole set of dependencies, without commensurate benefit.

**Comment by cmc333333** [comment]
I think there's a big use case for sharing the PDF draft -- I'm wondering if we can relegate its prominence, though, if we're concerned about processing time. You raise a great point about the similarity between what's already on screen and what the click through would be, @jmcarp.

This is probably just premature optimization. We don't know how big an impact any of this will have; let's see how it works in practice?

**Comment by jmcarp** [comment]
On the one hand, it's quick to expose pdf exports to users, so why not? I agree--will do this today.

On the other hand, we already know that a 1000-line html file takes ~15s to process on my laptop. I don't think any other endpoint in the app has the potential to take that long, so if I wanted to mess with the site, I'd target this one.

**Comment by jmcarp** [comment]
We're now using PDF for previews and comment submissions. The formatting and content of the PDF will need improvement, but that can be tracked in another issue. Closing!
