### ISSUE TITLE
Collect information about filer

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#39]
Sounds like we'll need to let users (optionally?) submit information about themselves along with their comments. Where should we collect this information along the comment submission flow? Should this be a separate screen, tab, accordion panel, etc.?

**Comment by donjo** [comment]
The current idea is that we'll collect this information on the same screen as the one where a comment filer reviews their comment. More information to come once we make some decisions on how we show that comment.

**Comment by cmc333333** [comment]
Note that these fields are dynamic (#48). Until that's worked out, ideally we'd be using a mocked config or something similar.

**Comment by jmcarp** [comment]
This is better captured in #48.
