### ISSUE TITLE
Show comment preview to users

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#40]
https://github.com/18F/regulations-site/pull/141 includes an endpoint to fetch a comment preview, but we don't show the preview on the frontend yet. Let's do that! We can either modify the preview endpoint to return HTML-ified markdown, or convert client-side. As in #39, I'm not sure how this should fit into the comment submission workflow (separate screens, etc.?).

@xtine and/or I can start on a working version now, or wait for designs. Thoughts @jehlers @donjo?

**Comment by cmc333333** [comment]
I think we should aim for the format we're planning to send to regs.gov -- if we're planning to use the comment field or just attach a plain text file, I don't think we should render the Markdown/whatever for the user.

If, instead, we're planning to attach an HTML file or a PDF, let's render the preview as HTML or a PDF.

**Comment by jmcarp** [comment]
How will regs.gov display comments (either from the comment field or attached files) in markdown or html--do they get rendered at all? I don't think it would be an awesome experience to write comments in wysiwyg, and then see a very different-looking preview of un-rendered markup. Would that weigh in favor of attaching a pdf?
