### ISSUE TITLE
Pending comments interface

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#41]
From the mocks:

<img width="180" alt="screen shot 2016-03-22 at 7 53 46 pm" src="https://cloud.githubusercontent.com/assets/1633460/13971619/f2026fac-f067-11e5-8034-9868555397c9.png">

Is this ready to start implementing @jehlers?

**Comment by jehlers** [comment]
@jmcarp That's still a wireframe, but I'd say its definitely worth starting to implement and if styles change we can update later. It is something I definitely want to be able to test, so the sooner something works the better. Do you agree @donjo?

**Comment by donjo** [comment]
Yep. I imagine the structure will stay the same but the styles may change so you can get started from an engineering perspective.

**Comment by jmcarp** [comment]
This exists now. The prototype definitely needs to be refined and styled, but it works!
