### ISSUE TITLE
[vuln] Cookies must be set to HttpOnly and must have secure settings

### ISSUE THREAD

**Issue by NoahKunin** [eregs/notice-and-comment#419]
Please consult the following and change config settings appropriately:

https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-SESSION_COOKIE_HTTPONLY -prevents cookies from be accessed via Javascript.

https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-SESSION_COOKIE_SECURE - clients will check for HTTPS before sending a cookie

https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-CSRF_COOKIE_SECURE  - `POST`s over HTTP w/cookies will be rejected. Defense in depth measure in case HTTPS Only controls fail.

**Comment by cmc333333** [comment]
These aren't vulnerabilities -- we don't use cookies.

**Comment by NoahKunin** [comment]
Hm - the system is definitely setting cookies for me. 

Reproduction: 

1. Go to https://eregsnc-demo.apps.cloud.gov/comments/review/0000_0000
1. Run `javascript:alert(document.cookie)` via the Chrome console
1. It returns the `csrftoken`. 

Screenshot:

<img width="1280" alt="screen shot 2016-06-29 at 1 30 20 pm" src="https://cloud.githubusercontent.com/assets/565071/16467780/a9cfae14-3dfd-11e6-83e2-24631b810693.png">

**Comment by cmc333333** [comment]
Looks like the cookies are coming from Google Analytics rather than the Django app.
