### ISSUE TITLE
Fix comment button positions, hover states

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#42]
We added per-section and per-paragraph comment buttons, but we need to bring the positions and hover states in line with mocks. Comment buttons should appear to the side of the corresponding content, and should change color (section-level) or visibility (paragraph-level) on hovering the content per @donjo.

I think @xtine may already be working on this--just filing for visibility.

**Comment by jmcarp** [comment]
Compare this:

<img width="719" alt="screen shot 2016-03-22 at 7 56 21 pm" src="https://cloud.githubusercontent.com/assets/1633460/13971680/835ae466-f068-11e5-8451-28c1cf6c9e41.png">

to this:

<img width="553" alt="screen shot 2016-03-22 at 7 59 22 pm" src="https://cloud.githubusercontent.com/assets/1633460/13971691/9ae5bd40-f068-11e5-8e00-899078232d3c.png">

**Comment by xtine** [comment]
I have a few things structured out, but I'm hesitant to push anything because I want the ok of @jehlers and @donjo first ... since using USWDS was discussed, I want to make sure what styles we are ok with going first before rearranging any css/markup.

**Comment by xtine** [comment]
These are mostly in place now, and button colors tentative and up to final styleguide #43
