### ISSUE TITLE
Decide CSS/design styleguide

### ISSUE THREAD

**Issue by xtine** [eregs/notice-and-comment#43]
Using some parts of the US Web Design Standards was discussed, but let's decide what we are going with if it's a hybrid of existing eregs, USWDS, and/or new styles specific to N&C.

Looping in @jehlers @donjo

**Comment by donjo** [comment]
So far, we are planning to use the [US Web Design Standards](https://playbook.cio.gov/designstandards) for most component and color palette decisions, with a few modifications. 

Some of the things that will be styled uniquely to N&C (but still fit within the design language USWDS lays the foundation for): 

- Body fonts received a slight modification to line-height to accommodate the unusual amount of text we're designing for 
- Tabs do not exist in USWDS. We'll be designing them from scratch using the bordered accordion design and side navigation designs as inspiration
- Text inputs and text areas will receive a different border styling based mostly on personal taste
- ...potentially more to come.

**Comment by jehlers** [comment]
- Using #f5f5f5 instead of #f1f1f1 for the lightest grey to help out with dark grey text on a light grey background contrast (especially in the left drawer)

**Comment by xtine** [comment]
We will need a button inactive state, and/or loading status. Once in a while the JS/server can be laggy and it would be nice to have some indication to the user that it is still loading and the button is inactive for that moment.
