### ISSUE TITLE
Parse additional notice meta data

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#44]
Our existing `notice` structure contains meta data around publication date, FR citations, etc. Based on the mockups, we'll need to also include

* agency information (may already be present)
* comment closing date
* mapping to regs.gov doc id (assumes #23)
* parsed contact info
* docket ids
* "name" of the notice
* RIN
* summary

<img width="939" alt="screen shot 2016-03-23 at 9 44 09 am" src="https://cloud.githubusercontent.com/assets/326918/13987027/fd4f3308-f0db-11e5-8ce1-54e13403290c.png">

**Comment by jehlers** [comment]
List of subjects on page 110 will probably come in handy.

**Comment by Journerdism** [comment]
done
