### ISSUE TITLE
Footnotes design

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#52]
Once we've decided the full break down for #34 we need to design what footnotes look like and how they work.

**Comment by cmc333333** [comment]
Ideally, this design would be shared with the CFR viewer (existing eregs)

**Comment by jehlers** [comment]
Initial designs that exist in eRegs:

#### Used in Section by section analysis screen for CFPB

(only had a screenshot from a design I tried w/ ATF)

![screen shot 2016-04-08 at 6 03 35 pm](https://cloud.githubusercontent.com/assets/4267825/14398696/359ef63c-fdb4-11e5-8af3-576a799a5b86.png)

#### Used for tables in ATF

![screen shot 2016-04-08 at 6 03 54 pm](https://cloud.githubusercontent.com/assets/4267825/14398712/4ffb0af2-fdb4-11e5-943e-c94b72b609c6.png)

**Comment by jehlers** [comment]
@donjo and I have agreed to use the normal CFPB design of footnotes for the notice and comment feature. We'll use Merriweather as the standard body copy for the content and Source Sans Pro for the numbers and header. Footnotes should appear at the bottom of each section, so in the case of the preamble, section I, II, or III.

**Comment by jehlers** [comment]
@xtine do you need anything else from me for this task? We want to use the CFPB (first one above) version so that users can click back to their original spot in the document.

**Comment by xtine** [comment]
@jehlers is the up arrow icon from fontawesome or a unique image?

**Comment by jehlers** [comment]
@xtine It's from the CFPB minicons

**Comment by xtine** [comment]
@jehlers: cool, I just implemented them. 😎

**Comment by donjo** [comment]
implemented in #163 and #162
