### ISSUE TITLE
Sidebar broken on regs

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#53]
https://github.com/18F/regulations-site/pull/146/files#diff-79ae6d8d1fd508c0f7f7084c33aeb989L77 made the `$definition` var a field. Need to update https://github.com/18F/regulations-site/blob/master/regulations/static/regulations/js/source/views/sidebar/sidebar-view.js#L85

**Comment by jmcarp** [comment]
gorramit
