### ISSUE TITLE
Determine requirements around showing regs.gov submission ID to users

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#54]
We may be required to show submission IDs from regs.gov to our users. The backend prototype isn't currently set up to do this--submitting a comment adds the job to a queue, and users don't have a way of knowing their comments were successfully submitted. If we have to (or want to) send this information back to users, we have a few options:

* Don't use a queue
* Attach a success callback to the submit task that alerts users (would require some contact information)
* Store a mapping of client IDs to regs.gov submission IDs, and poll from the client after submission until submission details are resolved

cc @cmc333333 @vrajmohan

**Comment by cmc333333** [comment]
Two other ideas:
* We could ask for an exemption / modification to the rules
* It's possible that comments can be submitted incrementally to regs.gov somehow -- perhaps we could post the comment immediately and _update_ it with the files

That said, I like the idea of having the users sit on a screen that updates with their submission details. We should probably avoid polling, but that's a implementation detail. I could imagine the page giving your submission's position in the queue for better feedback.

**Comment by jmcarp** [comment]
About that detail: how would we track work in the queue without polling? We could use SSE or websockets, but neither's Django-friendly (or WSGI-friendly, for that matter). The usual approaches for Django with server push are monkey-patching with gevent or running a separate tornado application, which seem like overkill here. We could use a managed service like fanout or pusher, which would probably be really cheap given our needs, but also possibly hard to procure.

**Comment by cmc333333** [comment]
Re polling: we can worth through it. My concern was that one of the big benefits of the queue system is that we can handle a larger user load; it seems like, if we have that many users polling our servers, we're effectively negating that benefit.

**Comment by jmcarp** [comment]
* The load on our servers from pinging should be way less than the load associated with submitting a comment. Most of the load associated with submitting is just waiting for a (synchronous) post to regs.gov, which I'm guessing could take a while. The ping should be very fast, since we'd probably be looking up a row in a table by primary key on a database on the same network as our application.
* Alternatively: instead of pinging our application, we could have the client ping an S3 key that will be created after the comment is submitted successfully--all we have to do is tell the client where the file's eventually going to live.
* Alternatively, we can write a tiny tornado application that talks to the client over websockets. On submitting a comment to the queue, we'd pass back a hard-to-guess channel ID. The client would subscribe to the channel, and tornado would notify on complete.

Also, are we sure we want to build this feature at all?

**Comment by cmc333333** [comment]
Internal discussion led to a good choice:
> instead of pinging our application, we could have the client ping an S3 key that will be created after the comment is submitted successfully--all we have to do is tell the client where the file's eventually going to live.

**Comment by jmcarp** [comment]
We may want to do more on this later on, like publishing error states (e.g. if comment submit fails a certain number of times), but we have a minimal working implementation. Closing.
