### ISSUE TITLE
Design and write content for the NC homepage

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#58]
Here's a very early wireframe:

![start homepage wireframe](https://cloud.githubusercontent.com/assets/4267825/14045989/b451932c-f274-11e5-8616-0dbf7b883c0f.png)

**Comment by jehlers** [comment]
@brittag would you be able to help with this a little bit?

**Comment by brittag** [comment]
Yes! Let's find a time to brain-transfer and I can work on this.

**Comment by brittag** [comment]
For our reference when we start working on this: EPA has a lot of content on its website about the regulatory process, and we should borrow from it and direct readers to it where appropriate. For example: [Regulations](https://www.epa.gov/laws-regulations/regulations), [Get Involved](https://www.epa.gov/laws-regulations/get-involved-epa-regulations), [Laws & Regulations](https://www.epa.gov/laws-regulations), [Docket Center](https://www.epa.gov/dockets).

**Comment by jehlers** [comment]
Current design directions:

![homepage 02 copy 2](https://cloud.githubusercontent.com/assets/4267825/14751489/23d72304-0898-11e6-9b08-0d37a8cd6e11.png)

![homepage 02 copy 5](https://cloud.githubusercontent.com/assets/4267825/14751495/277cb06e-0898-11e6-838e-7167207603aa.png)

![homepage 02 copy 6](https://cloud.githubusercontent.com/assets/4267825/14751499/2b868270-0898-11e6-82f2-2d95119975a9.png)

**Comment by jehlers** [comment]
Need to fix the "hero" image. Working on the following based on feedback:

- Keep stacked version of tool instructions because its easier to scan
- "Hero" needs most work
  - Pull out the date more
  - Make more of a call to action for the rules that are open for comment

**Comment by jehlers** [comment]
I'll finish the design for this task in #218! And then #219 when it's ready.
