### ISSUE TITLE
Design review page and regs.gov collection form

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#61]
![screen shot 2016-03-25 at 10 37 26 am](https://cloud.githubusercontent.com/assets/4267825/14046140/9921fc94-f275-11e5-9975-9ceedcc88c0b.png)

Some requirements for the comment form:
- Regs.gov logo needs to appear somewhere
- Need this text somewhere: “You are submitting an official comment to
Regulations.gov."
- Display the metadata fields specific to each agency’s comment form.
- Any additional metadata fields that are included on the form need to make clear that they are not provided to Regulations.gov since it is not part of our form.
- Indicate form fields that are required.
- Indicate form fields that will be publicly viewable on Regulations.gov.
- Display the following text: “You are filing a document into an official docket. Any personal information entered on this form may be publicly viewable on the web. I read and understand the statement above.”
- Next to the “I read and understand the statement above” text, include a check box that enables the comment button.
- Include a Submit button.
-  Links to both the User Notice and Privacy and Security Notice pages need to be included on the widget.
  - User Notice: http://www.regulations.gov/#!userNotice
  - Privacy and Security Notice: http://www.regulations.gov/#!privacyNotice

Here is EPA's current submission form:
![screen shot 2016-03-22 at 1 55 15 pm](https://cloud.githubusercontent.com/assets/4267825/14046227/4db59bb6-f276-11e5-8ce8-56d1c1d4b52b.png)

**Comment by jehlers** [comment]
For historical purposes, posting the first round of mockups and the feedback I got from the team.

#### Option 1

This first one is pretty basic, following what @jmcarp posted in #67. This one would identify where the attachments are connected, but would list them all together at the end. You can also edit each individual comment which would take users back to write mode for each of those comments.

![1](https://cloud.githubusercontent.com/assets/4267825/14090142/ae00bc0c-f506-11e5-83f8-7fe1eea06e5a.png)

#### Option 2

Wanted to try taking the preview of the comment out of the gray box, trying to use the edit this comment in the right sidebar.

![2](https://cloud.githubusercontent.com/assets/4267825/14090160/bedcf1da-f506-11e5-91e8-62a66b2f352f.png)

#### Option 3

Had to give the right sidebar a try… I don't think this is working because there are a lot of potential fields this would need to include (both for EPA and future agencies).

![3](https://cloud.githubusercontent.com/assets/4267825/14090183/df3eb454-f506-11e5-987a-e10dfd0bdc89.png)

#### Option 4

Gray stroke around the review section, feels more like a preview to me.

![4](https://cloud.githubusercontent.com/assets/4267825/14090201/ebb665c4-f506-11e5-949f-e5a9e1497b7e.png)

#### Option 5

Trying to integrate the contact information form into the review section a little more.

![5](https://cloud.githubusercontent.com/assets/4267825/14090216/fc1465ba-f506-11e5-9bdb-341d11273006.png)

#### Feedback from the team: Combo of 2, 3, and 5

- needs a "download this draft" kind of button (same as #67)
- include ^ download button on confirmation screens (the user is downloading a draft on this screen and a final record on the confirmation screen)
- we like the document type feel of the white background and gray stroke
- bring “edit” links into the sidebar to match that interaction everywhere else
- play with putting the attachments separate from the “final comment”
- play with how close the “final comment” looks to the data sent to regs.gov

**Comment by jehlers** [comment]
Updated mock ups based on the feedback above:

![review 02 copy 2](https://cloud.githubusercontent.com/assets/4267825/14152331/b786cd72-f680-11e5-9785-4cc35de6fe79.png)

**Comment by jmcarp** [comment]
Did we decide to submit comments as PDFs, or is PDF a placeholder for whichever format we pick?

Also (sorry to only ever complain!), I think it's a little surprising that users can (kind of) edit attachments on the review interface--looks like attachments can be removed but not added, and text can't be edited. To me, all editing actions happen in the edit interface, and nowhere else. This isn't hard to implement, but it goes against my habit of implementing an interaction just once in the code, and just once in the UI.

**Comment by jehlers** [comment]
I think we are leaning towards PDFing the comments at this stage. 

The review mode is not editable, if someone wants to edit their comment they will be taken back to write mode. To keep this consistent with the attachments, I took out the ability to remove an attachment from this page. 

We are also assuming that anyone who uses the "Download the full text of this comment as a PDF" at this stage is downloading a draft document. We'll want to make sure there is some kind of draft watermark on the pdf they download. Once they have submitted to regs.gov, on the confirmation page, we'll have a button that allows users to download the official record of the comment was sent to the docket. cc #67 

![review 02 copy 2](https://cloud.githubusercontent.com/assets/4267825/14155045/ebfd4556-f68d-11e5-9e89-a350fbd7bee3.png)

The copy is still up for grabs a little. I know @brittag had a better idea for what the "Download the full text of this comment as a PDF" link could say.

Here's how we think the form can work. We'll still have to pass this by EPA's legal team.

The checkboxes can both be clicked, but hopefully people won't. We're trying to organize the fields based on how people will need to give their information. 

The biggest change here is using the "Submitter's Representative" field as a "your name" field so that it is open for users who are not submitting on behalf of a third party.

If the user is part of an organization:

![review 02 copy 3](https://cloud.githubusercontent.com/assets/4267825/14155185/a33d66f6-f68e-11e5-9dfe-9ba61bc380c6.png)

If they are part of a government agency:

![review 02 copy 4](https://cloud.githubusercontent.com/assets/4267825/14155192/a986fe50-f68e-11e5-9b00-80602556cada.png)

**Comment by brittag** [comment]
I think the "Include your information (optional)" and "(Required to submit.)" sections could have separate titles to help people understand what's optional or required at a glance, such as like this (which I know has the wrong font):

![a986fe50-f68e-11e5-9b00-80602556cada](https://cloud.githubusercontent.com/assets/391313/14267783/72ddf9e6-fa88-11e5-8bcf-aa2b09dac495.png)

**Comment by jehlers** [comment]
@brittag I like that, but I think we should continue to speak to the user who is submitting the comment. How do you feel about breaking it up a little more into it's own section by naming it "SUBMIT YOUR COMMENT" or "Ready to submit your comment?" or "SUBMIT YOUR COMMENT TO EPA." 

I'm also second guessing if we need the required text... the user will not be able to bypass the submit button until they check the box. The disabled to enabled interaction does inherently say "this action is required."

On another note, if the "(OPTIONAL)" being in the header is the confusing part, what if we moved it down to the "Your name (optional)" line? That way the optional text is directly related to the form elements and not the whole section?

**Comment by brittag** [comment]
I do like the idea of finding a friendlier title than "Confirm submitting public comment (required)"!

We could try "Submit your comment" as the title and move "(required)" back to the end of the "I read and understand" checkbox label. ("Ready to submit your comment?" is nicely conversational, but I like matching the format of the other titles, which are all declarative rather than questions.)

It'd be good to have "(optional)" and "(required)" in matching locations in these two sections, but I'm not sure if moving "(optional)" to "Your name" would help, since then it could be ambiguous whether the "submitting on behalf" checkboxes are optional.

Would "Submit your comment (required)" be confusing as a title for the second section? (You're not required to submit your comment, you're just required to check the box if you want to submit your comment.)

I'll keep thinking on other options here!

**Comment by jehlers** [comment]
Yeah I like all of those thoughts! I see the confusion there with "you're not required to submit your comment," but not quite sure how to avoid that. I would hope that if you've made it this far then you want to submit your comment so that distinction may not be important?

**Comment by brittag** [comment]
That's a good point, in context "Submit your comment (required)" probably wouldn't sound weird to anyone - they already know that they are participating in a voluntary process, so it'd be clear that this is just a required step for submission.
