### ISSUE TITLE
Design sections after the preamble that include the actual regulation changes

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#63]

**Comment by jehlers** [comment]
Here are some designs for the parts of the rule that show actual changes to regulation text. 

Following the interactions laid out in #80, because the text of the preamble is so long (meaning that the table of contents itself will be very long) we have broken out these changes into their own navigation tab in the left drawer labeled "CFR." This will hopefully differentiate the two parts of the rule and allow for easy access to both.

#### Diff mode is always on

Because the rule only shows the changes to the regulation text, we feel that eRegs can add the most context by always showing the differences between the current law and the new proposed changes. This will hopefully allow users to more quickly see exactly what is changing in this new rule.

We will also keep the instructions for what is being added to the regulation to keep the context that this document is the notice in the FR, not the regulation.

In addition, for context, if the user wants to see the rest of the text in a section surrounding the paragraphs that are changing, they could expand the normal *'s that indicate something is missing to see the other paragraphs as they are currently written in the regulation. 

![1](https://cloud.githubusercontent.com/assets/4267825/14190614/c09aa3d4-f761-11e5-883f-04854bedf6a2.png)

#### If whole new sections or subparts are added

Generally if a whole new section is added to a regulation, the user will see all green. But if a subpart is added, we still want to load data by section to preserve easy navigation through the changes and to match the normal way users navigate through the eRegs tool.

The design of this was tricky, however, because the instructions talk about adding a subpart, not the individual sections. So, we've added the ability to have the subpart name on the page, and show where in the subpart the current section you are viewing lives.

![2](https://cloud.githubusercontent.com/assets/4267825/14191944/948b23e8-f768-11e5-9423-dcb0c7068adc.png)

#### Switching from the preamble to the CFR changes

The last part that is tricky is what happens when the user gets to the end of the preamble and needs to switch to the new tab? 

One way of doing this may be to follow the ending of the document and allude to the next section like this:

![3](https://cloud.githubusercontent.com/assets/4267825/14191988/e7bb063c-f768-11e5-812e-95981ca24a6e.png)

Thoughts?

**Comment by cmc333333** [comment]
Quick note that the director's signature and the "For the reasons" paragraphs aren't considered part of the preamble, at least according to the XML. I'd suggest pulling the signature into its own LHS section? I think we can just skip over the "For the reasons set forth" bit.

**Comment by jehlers** [comment]
@cmc333333 I agree that I think we can ignore the "For reasons..." text if we want to, but I was thinking about how to transition someone from the end of the preamble to the next "tab" for the CFR changes. I don't think a page with just the signature is helpful, I'm not sure we need that on its own either. Would it be hard to pull this data onto this "last page" before the CFR change start? Maybe at least the signature since it "ends" the preamble?
