### ISSUE TITLE
Allow for the user to download the preview/doc that will be sent to regs.gov

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#67]

**Comment by jmcarp** [comment]
@jehlers should the downloaded preview document include attachments or links to attachments, or just refer to them by name like the preview we're showing now? This might change (see #38), but the current preview looks like this:

```markdown
# 2016_02749/I
bob

## Attachments
* lob.txt

# 2016_02749/II/A
law
```

Meaning attachments are listed out by file name, but there's no link included.

**Comment by jehlers** [comment]
This is being taken care of in #61, so I'm going to close this issue. Thank you for the screenshot here @jmcarp, it helped me a lot with the design.
