### ISSUE TITLE
Web Editors

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#7]
If we won't have access to the proposed rule in a machine-readable format, we may need to copy-paste the word/pdf doc into something more structured. Quick research on web editors which might make this process simpler:

### XML-specific
Minimally, we can provide a nice XML editor and validate it against a schema.

* http://unc-libraries.github.io/jquery.xmleditor/ has a nice nested abstraction for viewing/editing the XML. Probably too geeky
* https://github.com/umd-mith/angles appears to be dead, but worth a look due to its overlapping goals: "a lightweight, online XML editor tuned to the needs of the scholarly text encoding community"
* http://holloway.co.nz/doctored/ minimally documented and may be dead, but has a relatively nice interface
* http://www.lexiconista.com/xonomy/ solid XML editor. Minimal abstractions for the UI.
* http://wymeditor.github.io/wymeditor/dist/examples/15-rdfa-editor.html geared at XHTML, but might work more broadly. Ugly.

### Structured Input
On the other hand, there are a few text editors which have structured input

* http://madebymany.github.io/sir-trevor-js/ I have a soft spot for this project, despite it being poorly documented and under heavy development. I like the "block" concept of structure a great deal.
* http://prosemirror.net/ closer to a WYSIWYG but with semantic markup
* http://clearly.pl/tutorial/ interesting but doesn't seem customizable enough for our needs
* http://joshondesign.com/p/projects/semantic-editor-js/sample/editortest.html# blocks and inline components. Minimal, but could generate nice output

**Comment by grapesmoker** [comment]
Honestly, I have not found a single XML editor that offers the kind of convenience that I would want. I've probably looked at every commercial tool out there, and there's nothing that I prefer to some combination of Emacs and Eclipse. The only other project of comparable quality is xmlcopyeditor, which I'm not sure if it will run on Macs but definitely runs just fine on Linux. None of these are web tools, but no web tool that I have ever seen can even come close to their functionality.

**Comment by cmc333333** [comment]
We use prosemirror for comment editing, but didn't need anything for editing XML.
