### ISSUE TITLE
Show comments in order

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#73]
In the comment index and comment review views, comments are displayed in the order in which the user added them, not in section order. I would guess that section order is better here.

cc @cmc333333

**Comment by jmcarp** [comment]
Turns out that https://github.com/eregs/regulations-site/pull/213 adds an `indexes` field to nodes in `HTMLBuilder`, which we can pass through to the frontend for ordering once that PR is ready to merge.

**Comment by cmc333333** [comment]
Resolved via eregs/regulations-core#54 and eregs/regulations-site#347
