### ISSUE TITLE
Fix sub-section comment labels

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#79]
With the addition of human-readable section labels, it looks like we lost per-paragraph labels for the commenting interface (note that all labels have the same text below):

<img width="933" alt="screen shot 2016-03-30 at 12 55 24 pm" src="https://cloud.githubusercontent.com/assets/1633460/14150554/93a8a398-f677-11e5-8ca3-235c763cdad8.png">

Seems like we'll want every commentable entity to get a label that's both unique *and* human-readable, so that we can summarize comments in a useful way. @cmc333333: what do you think about adding paragraph numbers to human-readable labels? Or is there a better approach here?

**Comment by cmc333333** [comment]
Latest word is:
* tie a comment to the most specific paragraph possible -- a comment about Section III.A is different than Section III.A paragraph 3
* in `read` view, we should always say "Write a comment about this paragraph" when it's not a header (i.e. `not node.title`)
* in `write` view (when listing comments), show the long form

I think that means we need to
1. Modify the `read` view text
2. Add paragraph index to the human label. Note that this should not be derived from the label itself (i.e. it should not be "4" in `blahblah-I-B-p4`) as that's not super dependable. Preferably, we'd use the index of the child in it's parent.

**Comment by jmcarp** [comment]
Is it possible to encounter labels like `['III', 'A', 'p1', 'p7']`? I noticed something like this in the tests. If so, should comments be allowed on p1-p7, and how should that node be labeled?

**Comment by cmc333333** [comment]
I don't think this can happen in a preamble with our existing code, but I wouldn't want to rule it out completely. We do want to allow comments on as deeply nested paragraphs as possible. As for how to label it, I think you should go ahead and pick a scheme. For example, maybe it's just:
```
Section III.A paragraph 4, subparagraph 9, subparagraph 3
```
