### ISSUE TITLE
Table of contents interactions

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#80]
While working on #63, we realized that the part of the rule that list changes to the CFR is structured very differently from the rest of the preamble. This has forced us to break the table of contents into 2 parts: the preamble, and the CFR. These TOC's should look and act similarly from a user standpoint, but their structure is different functionally. The styles are being worked on, but I wanted to post these to show functionally and structurally how we want to build each tab.

#### Preamble TOC

The preamble for this rule is particularly well structured, but we are aware (see #11) that other preambles in proposals can be structured differently. The roman numeral sections are similar to subparts in a regulation if the preamble/rule is particularly long (as this one is), however, in shorter preambles they can be just sections. Because of this, we need to account for showing I, II, III level text as well as allow the user to navigate one level down in the outline structure for easy access to specific issues inside the proposal.

Here's what we're thinking:
- The user can click on the roman numeral levels AND the A, B, C levels.
- What loads in the content section: the whole content of the larger I, II, III sections. 
- If a user clicks on an A, B, C level, they will be scrolled to that part of the larger section.

This gives users more context around each A, B, C, level issues, but also allows for text outside of this structure (in case there is a paragraph or more above the first A). 

![screen shot 2016-03-30 at 4 46 54 pm](https://cloud.githubusercontent.com/assets/4267825/14157117/a324d89e-f697-11e5-812e-1011d9c6e9b5.png)

Another way to look at a section that is ON would be something like this:

![screen shot 2016-03-30 at 4 47 06 pm](https://cloud.githubusercontent.com/assets/4267825/14157331/8aaea03c-f698-11e5-99e9-74c264dd8870.png)

This interaction is something we want to test in the next week or so.

#### CFR TOC

The CFR tab shows the text of what is changing in the regulation. Since more than one regulation is changing in this rule, we need to show that. The regulation number is not clickable like the roman numeral sections above are. But all sections with black text are. This section level navigation matches eRegs' normal TOC structure and organization.

![screen shot 2016-03-30 at 5 04 04 pm](https://cloud.githubusercontent.com/assets/4267825/14157577/966d7b54-f699-11e5-8987-7f513a9c64af.png)

**Comment by cmc333333** [comment]
Preamble, as separate tasks: #109, #105
