### ISSUE TITLE
read/write tab polish

### ISSUE THREAD

**Issue by donjo** [eregs/notice-and-comment#97]
![screen shot 2016-04-04 at 4 20 04 pm](https://cloud.githubusercontent.com/assets/776987/14263688/8f471a74-fa81-11e5-9891-2bb0428a3f9f.png)

there's a little 1px overhang on these tabs that may have resulted from our top nav going from 60px in -site to 56px in notice-and-comment. Adding `height: 33px` to `.preamble-header .read-proposal, .preamble-header .write-comment {` is one option to fix. The other being re-calculate some of the heights on `.sub-head` and others that are defined in `em` units

I'm also thinking of maybe 2 other things, maybe making the tabs a little bit tighter (225px width instead of 245px) and using the semibold (weight 600) font. Ex:

![screen shot 2016-04-04 at 4 34 11 pm](https://cloud.githubusercontent.com/assets/776987/14263975/45260d90-fa83-11e5-8f1a-f755ab61817b.png)

**Comment by jehlers** [comment]
Also, not sure this is the right place for this, but the gray background of the tabs / subheader should be the same #f5f5f5 as the drawer background for A) consistency and B) help w/ 508 compliance with the gray text.

![screen shot 2016-04-05 at 1 34 00 pm](https://cloud.githubusercontent.com/assets/4267825/14291752/050021be-fb33-11e5-9927-d66d2d1e8de4.png)
